### ISSUE TITLE
Infografia gestion de proyectos_abigail coronel

### ISSUE THREAD

**Issue by abicoronel** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-abicoronel#2]
[infografia gestion de proyectos.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-abicoronel/files/12457724/infografia.gestion.de.proyectos.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 19
Debió ser una sola hoja.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado...
